// Copyright 2018-2020 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file

package main

import (
	"bytes"
	"encoding/csv"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"slices"
	"strings"
	"text/template"

	"github.com/otfabric/go-opcua/internal/goname"
)

type idRow struct {
	GoName   string
	SpecName string
	Value    string
}

func main() {
	log.SetFlags(0)

	in := flag.String("in", "schema/NodeIds.csv", "path to NodeIds.csv")
	out := flag.String("out", "id/id_*_gen.go", "path to generated file")
	flag.Parse()
	if !strings.ContainsRune(*out, '*') {
		log.Fatal("out must contain a wildcard")
	}

	if *in == "" {
		log.Fatal("-in is required")
	}
	if *out == "" {
		log.Fatal("-out is required")
	}

	f, err := os.Open(*in)
	if err != nil {
		log.Fatalf("Error reading %s: %v", *in, err)
	}
	defer func() { _ = f.Close() }()

	rows, err := csv.NewReader(f).ReadAll()
	if err != nil {
		log.Fatalf("Error parsing %s: %v", *in, err)
	}

	type groupData struct {
		NodeClass string
		Rows      []idRow
	}

	grouped := map[string]*groupData{}
	seen := map[string]string{} // goName → specName for collision detection

	for _, row := range rows {
		specName := row[0]
		value := row[1]
		nodeClass := row[2]

		goN := goname.Format(specName)

		if !goname.IsValidIdent(goN) {
			log.Fatalf("invalid Go identifier %q (from spec name %q)", goN, specName)
		}

		if prev, ok := seen[goN]; ok && prev != specName {
			log.Fatalf("collision: spec names %q and %q both normalize to Go identifier %q", prev, specName, goN)
		}
		seen[goN] = specName

		g, ok := grouped[nodeClass]
		if !ok {
			g = &groupData{NodeClass: nodeClass}
			grouped[nodeClass] = g
		}
		g.Rows = append(g.Rows, idRow{GoName: goN, SpecName: specName, Value: value})
	}

	for nodeClass, g := range grouped {
		out := strings.ReplaceAll(*out, "*", nodeClass)
		var b bytes.Buffer
		if err := idTmpl.Execute(&b, g); err != nil {
			log.Fatalf("Error generating code: %v", err)
		}

		bfmt, err := format.Source(b.Bytes())
		if err != nil {
			log.Fatalf("Error formatting code: %v", err)
		}

		if err := os.WriteFile(out, bfmt, 0644); err != nil {
			log.Fatalf("Error writing %s: %v", out, err)
		}
		log.Printf("Wrote %s", out)
	}

	{
		out := strings.ReplaceAll(*out, "*", "names")
		nameOrder := make([]string, 0, len(grouped))
		for k := range grouped {
			nameOrder = append(nameOrder, k)
		}
		slices.Sort(nameOrder)

		var b bytes.Buffer
		if err := nameTmpl.Execute(&b, nameOrder); err != nil {
			log.Fatalf("Error generating code: %v", err)
		}

		bfmt, err := format.Source(b.Bytes())
		if err != nil {
			log.Fatalf("Error formatting code: %v", err)
		}

		if err := os.WriteFile(out, bfmt, 0644); err != nil {
			log.Fatalf("Error writing %s: %v", out, err)
		}
		log.Printf("Wrote %s", out)
	}

	fmt.Fprintf(os.Stderr, "id: %d identifiers, 0 collisions\n", len(seen))
}

var idTmpl = template.Must(template.New("").Parse(`
// Copyright 2018-2024 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/id. DO NOT EDIT!

package id

const (
	{{range .Rows}}{{.GoName}} = {{.Value}}
	{{end}}
)

var name{{.NodeClass}} = map[uint32]string{
	{{- range .Rows}}
	{{.Value}}: "{{.SpecName}}",
	{{- end}}
}
`))

var nameTmpl = template.Must(template.New("").Parse(`
// Copyright 2018-2024 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/id. DO NOT EDIT!

package id

import "strconv"

func Name(id uint32) string {
	{{- range .}}
	if s, ok := name{{.}}[id]; ok {
		return s
	}
	{{- end}}
	return strconv.FormatUint(uint64(id), 10)
}
`))
